import Head from "next/head";

import { Parallax, ParallaxBanner, useParallax } from "react-scroll-parallax";
import Marquee from "react-fast-marquee";

export default function Home() {
  const parallax = useParallax({
    speed: -10,
  });

  return (
    <div>
      <Head>
        <title>Alain Logo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favico.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Space+Mono&display=swap"
          rel="stylesheet"
        />
      </Head>
      <div className="menu">
        <span className="wrap wrap1">
          <h1>
            <a href="#" className="app-item">
              <div>
                <span className="app-item-text">LOGO</span>
              </div>
            </a>
          </h1>
        </span>
        <span className="wrap wrap2">
          <h1>
            <a
              href="mailto:alaindev54@gmail.com"
              target="_blank"
              rel="noreferrer"
            >
              <div className="app-item">
                <div>
                  <span className="app-item-text">EMAIL</span>
                </div>
              </div>
            </a>
          </h1>
        </span>
      </div>
      <main ref={parallax.ref} className="main">
        <header id="#header" className="header">
          <div className="header_centre">
            <div className="header_text">
              I&apos;m Alain Logo, a French developer, currently living between
              Annecy and North of France.
            </div>
          </div>

          <div className="header_scroll">
            <div className="h1_box">
              <Parallax translateX={["100px", "0px"]} easing="easeInQuad">
                {" "}
                <div className="h1_haut">
                  <h1>
                    <span>interface</span>
                    <span className="bord">interface</span>
                    <span>interface</span>
                    <span className="bord">interface</span>
                    <span>interface</span>
                  </h1>
                </div>
              </Parallax>

              <Parallax translateX={["-200px", "0px"]} easing="easeInQuad">
                <div className="h1_bas">
                  <h1>
                    <span className="bord">developer</span>
                    <span>developer</span>
                    <span className="bord">developer</span>
                    <span>developer</span>
                    <span className="bord">developer</span>
                    <span>developer</span>
                  </h1>
                </div>
              </Parallax>
            </div>
          </div>
        </header>
        <Parallax translateY={["270px", "-400px"]}>
          <div className="trop">
            <div className="header_img "></div>
          </div>
        </Parallax>

        <Parallax translateY={["0px", "150px"]}>
          <div className="prese">
            I studied programming at school during 4 years where i profounded
            knowledge in web design and mobile responsive.
          </div>
        </Parallax>
        <div className="skills">
          <Marquee gradient={false} speed={60} pauseOnHover={true}>
            <p>
              HTML5 - <span className="skills_vide"> CCS3 - </span>Javascript -{" "}
              <span className="skills_vide"> Figma - </span>
              NodeJS - <span className="skills_vide"> ReactJs - </span>NextJs -{" "}
              <span className="skills_vide"> AngularJs - &nbsp;</span>
            </p>
          </Marquee>
          <Marquee
            gradient={false}
            speed={60}
            direction={"right"}
            pauseOnHover={true}
          >
            <p>
              <span className="skills_vide"> PHP - </span>MySQL -{" "}
              <span className="skills_vide"> MongoDB - </span>Wordpress -{" "}
              <span className="skills_vide"> Prestashop - </span> GitHub -
              &nbsp;
            </p>
          </Marquee>
        </div>

        <section id="travaux" className="section_travaux">
          <div className="titre titre_travaux">
            <span id="intro" className="bord">
              works
            </span>
            <span>works</span>
            <span className="bord">works</span>
          </div>

          <div className="ligne ligne1">
            <div className="projet projet1">
              <div className="desc">
                <div className="nom">
                  <p className="client">AlpinStore / PIM</p>
                  <p className="annee">2022</p>
                </div>
                <a
                  href="https://www.alpinstore.com/fr/"
                  target="_blank"
                  rel="noreferrer"
                >
                  <div className="desc_img"></div>
                </a>
                <div className="info">
                  <p className="type">e-commerce</p>
                </div>
              </div>
            </div>

            <div className="projet projet2">
              <div className="desc">
                <div className="nom">
                  <p className="client">Talentissim</p>
                  <p className="annee">2022</p>
                </div>
                <a
                  href="https://talentissim.fr/"
                  target="_blank"
                  rel="noreferrer"
                >
                  <div className="desc_img"></div>
                </a>
                <div className="info">
                  <p className="type">service</p>
                </div>
              </div>
            </div>
          </div>

          <div className="ligne ligne2">
            <div className="projet projet4">
              <div className="desc">
                <div className="nom">
                  <p className="client">Stella Green</p>
                  <p className="annee">2021</p>
                </div>
                <a
                  href="https://stellagreen.fr/"
                  target="_blank"
                  rel="noreferrer"
                >
                  <div className="desc_img"></div>
                </a>
                <div className="info">
                  <p className="type">e-commerce</p>
                </div>
              </div>
            </div>

            <div className="projet projet3">
              <div className="desc">
                <div className="nom">
                  <p className="client">Atout Beauté</p>
                  <p className="annee">2021</p>
                </div>
                <a
                  href="https://atoutbeaute.fr/"
                  target="_blank"
                  rel="noreferrer"
                >
                  <div className="desc_img"></div>
                </a>
                <div className="info">
                  <p className="type">e-commerce</p>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section className="section_contact">
          <div className="titre titre_contact">
            <span className="bord">contact</span>
            <span className="bord2">contact</span>
            <span className="bord">contact</span>
            <Parallax translateY={["-150px", "-500px"]}>
              <div className="contact_img"></div>
            </Parallax>
          </div>

          <div className="contact">
            <div className="contact_text">
              <p>
                If you have some ideas or projects you can contact me. I&apos;m
                always available to chat and i&apos;ll happily answer your
                questions.
              </p>
            </div>
            <div className="me_contact">
              <p>
                <a
                  target="_blank"
                  rel="noreferrer"
                  href="mailto:alaindev54@gmail.com"
                >
                  alaindev
                  <br />
                  54@gmail.com
                </a>
              </p>
            </div>
            <div className="marquee marquee_mail">
              <Marquee gradient={false} speed={70}>
                <p>
                  send me an email&nbsp;
                  <span className="marquee_vide"> send me an email &nbsp;</span>
                  send me an email&nbsp;
                  <span className="marquee_vide"> send me an email &nbsp;</span>
                  send me an email&nbsp;
                  <span className="marquee_vide"> send me an email &nbsp;</span>
                  send me an email&nbsp;
                  <span className="marquee_vide"> send me an email &nbsp;</span>
                  send me an email&nbsp;
                  <span className="marquee_vide"> send me an email &nbsp;</span>
                  send me an email&nbsp;
                  <span className="marquee_vide"> send me an email &nbsp;</span>
                  send me an email&nbsp;
                  <span className="marquee_vide"> send me an email &nbsp;</span>
                  send me an email&nbsp;
                  <span className="marquee_vide"> send me an email &nbsp;</span>
                  send me an email&nbsp;
                  <span className="marquee_vide"> send me an email &nbsp;</span>
                  send me an email&nbsp;
                  <span className="marquee_vide"> send me an email &nbsp;</span>
                  send me an email&nbsp;
                  <span className="marquee_vide"> send me an email &nbsp;</span>
                  send me an email&nbsp;
                  <span className="marquee_vide"> send me an email &nbsp;</span>
                  send me an email&nbsp;
                  <span className="marquee_vide"> send me an email &nbsp;</span>
                  send me an email&nbsp;
                  <span className="marquee_vide"> send me an email &nbsp;</span>
                  send me an email&nbsp;
                  <span className="marquee_vide"> send me an email &nbsp;</span>
                  send me an email&nbsp;
                  <span className="marquee_vide"> send me an email &nbsp;</span>
                  send me an email&nbsp;
                  <span className="marquee_vide"> send me an email &nbsp;</span>
                  send me an email&nbsp;
                  <span className="marquee_vide"> send me an email &nbsp;</span>
                </p>
              </Marquee>
            </div>
            <div className="contact_link">
              <div className="links">
                <ul>
                  <li>
                    <a
                      target="_blank"
                      rel="noreferrer"
                      href="https://www.linkedin.com/in/alain-logossoukpe-500323217/"
                    >
                      linkedin
                    </a>
                    <span></span>
                  </li>
                  <li>
                    <a
                      href="https://github.com/alainlogo"
                      target="_blank"
                      rel="noreferrer"
                    >
                      github
                    </a>
                    <span></span>
                  </li>
                  <li>
                    <a
                      href="https://www.instagram.com/cozy.jsx/"
                      target="_blank"
                      rel="noreferrer"
                    >
                      instagram
                    </a>
                    <span></span>
                  </li>
                </ul>
              </div>
              <p>2023</p>
            </div>
          </div>
        </section>

        <div id="app">
          <div id="hero"></div>
        </div>
      </main>
    </div>
  );
}
